In [31]:
import numpy as np
a = [1, 2, 3]
b = [4, 5, 6]
p = -1
result = np.zeros(len(a)*len(a))
print(result)
for i in range(0,len(a)): # 0 ~ 3
#     print(i)
    for j in range(0,len(a)):
#         print(i,j)
        p = p + 1
        result[p] = a[i] - b[j]
        print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-3.  0.  0.  0.  0.  0.  0.  0.  0.]
[-3. -4.  0.  0.  0.  0.  0.  0.  0.]
[-3. -4. -5.  0.  0.  0.  0.  0.  0.]
[-3. -4. -5. -2.  0.  0.  0.  0.  0.]
[-3. -4. -5. -2. -3.  0.  0.  0.  0.]
[-3. -4. -5. -2. -3. -4.  0.  0.  0.]
[-3. -4. -5. -2. -3. -4. -1.  0.  0.]
[-3. -4. -5. -2. -3. -4. -1. -2.  0.]
[-3. -4. -5. -2. -3. -4. -1. -2. -3.]


In [112]:
x = [1,2,3,4,5]
y = [4,5,6]

result = [a - b for a in x for b in y]
result
print(type(x))

<class 'list'>


In [72]:
z = [q for q in x for w in y if q in x]
z


[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]

In [117]:
print(type(x))
p = sorted(set(x).intersection(y))
print(type(x))
print(p)
print(type(p))

<class 'set'>
<class 'set'>
['c']
<class 'list'>


In [108]:
sorted(set(y).difference(x))
print(type(y))

<class 'list'>


In [82]:
q for q in x:
    print(q)

SyntaxError: invalid syntax (<ipython-input-82-38945c89ed6e>, line 1)

In [110]:
l = np.intersect1d(x,y)
print(l)
print(type(l))

[]
<class 'numpy.ndarray'>


In [95]:
result = x.intersection(y)
result

AttributeError: 'list' object has no attribute 'intersection'

In [116]:
x = {"a", "b", "c"}
y = {"c", "d", "e"}
z = {"f", "a", "c"}

result = x.intersection(y, z)

print(result)
print(type(x))

{'c'}
<class 'set'>


In [123]:
x = np.arange(1,10).reshape(3,3)

y = [ i[0] for i in x]
y

[1, 4, 7]