In [4]:
import numpy as np
np. __version__ # 버전 확인
#axis 0,1,2 로 3D array까지 표현 

'1.19.1'

In [13]:
a1 = np. array([1,2,3,4,5]) # 1차원 배열
print(a1)
print(type(a1)) # numpy.ndarray n차원을 의미
print(a1.shape) # 배열에 대한 모양 5개의 엘레먼트들이 있다, 뒤에 아무것도 없음 ㅡ 1차원 배열이구나
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [19]:
a2 = np.array([ [1,2,3], [4,5,6],[7,8,9] ])
print(a2)
print(a2.shape) # 3,3 3by3 array
print(a2[0,0], a2[1,1], a2[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [25]:
a3 = np.array([ [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ] ])
print(a3)
print(a3.shape) # 3,3,3
np.zeros(10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [34]:
np.eye(3) #단위행렬 n,n 에만 1 임 나머지 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.tri(3) #삼각행렬 삼각모양이 1 나머지 0

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [38]:
np.empty(10) 
'''
초기화되지 않은 배열 생성
초기화를 하지 않기 때문에 어떤 배열 생성보다 저렴하고 빠르게 생성함
초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음 -> 어떤값이올지모름
'''


''

In [41]:
print(a1)
np.zeros_like(a1) #a1의 shape과 같은 모양으로 0을 채운것을 생성

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [43]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
print(a3)
np.full_like(a3,10) # a3 뒤에 어떤 값으로 채울지 넣어줘야함

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [47]:
np.arange(0, 30, 2) #0 ~ 30 까지 2 간격으로 = range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [49]:
 np.linspace(0, 1, 5) # 0~1을 균등하게 5개로 나눔 첫 0 마지막 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:
np.logspace(0.1, 1, 20) # 로그 스케일형태로 구성 

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [54]:
#랜덤값으로 배열 생성하는 방법도 있음
np.random.random((3,3)) #shape만 주고 실수값으로 나옴


array([[0.75164829, 0.09821198, 0.257395  ],
       [0.28761215, 0.36894125, 0.17781241],
       [0.94719547, 0.15182004, 0.78885359]])

In [58]:
np.random.randint(0, 10, (3,3)) #랜덤 정수 range를 넣어줌 

array([[6, 2, 8],
       [3, 5, 8],
       [2, 1, 1]])

In [79]:
np.random.normal(0, 1, (3,3)) # size(3,3) 로 해도됨 평균,표준편차를 주어줌

array([[-0.16937298,  0.3039671 ,  0.30109984],
       [ 0.94434459, -0.60104754, -0.47678564],
       [-0.72023983, -0.52840518, -0.39692286]])

In [81]:
np.random.rand(3,3) # 유니폼 형태로 만들어줌

array([[0.88372756, 0.13798291, 0.34715848],
       [0.21118093, 0.66050073, 0.51474476],
       [0.28930453, 0.85667326, 0.14576761]])

In [83]:
np.random.randn(3,3) #표준정규분포를 고려해서 랜덤의 수로 배열 생성

array([[ 1.69657134, -0.02734479,  0.56264876],
       [ 0.94727087,  1.46944527, -0.21901679],
       [ 1.11452589,  1.30926037,  1.91392686]])

In [85]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
np.ones((3,3), dtype=bool) # 1 = True

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [90]:
np.full((3,3), 1.0, dtype=float) #1.0으로 생성

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
#날짜/시간 배열 생성
date = np.array('2020-01-01', dtype=np.datetime64) # string 인데도 날짜 타입인걸로 알수있음
date 

array('2020-01-01', dtype='datetime64[D]')

In [95]:
date + np.arange(12) #날짜계산

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [97]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [101]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') #나노초면 뒤에 ns를 붙여줌
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [110]:
#배열 속성 정보
def array_info(array):
    print(array)
    print("ndim:", array.ndim) # 1차원
    print("shape:", array.shape) #5개의 엘리먼트
    print("dtype:", array.dtype) #인트
    print("size:", array.size) # 5
    print("itemsize:", array.itemsize) # 각 하나의 아이템이 가지는 사이트 8nyte =>int32 이므로 4
    print("nbytes:", array.nbytes) #전체 바이츠 4*5 = 20
    print("strides:", array.strides) #다음 엘리먼트(차원)으로 가기위한 사이즈 = 4 가 필요

In [113]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [115]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


In [117]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


In [119]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [124]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [129]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1]) # 여기까지가 인덱싱

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


In [136]:
print(a1)
print(a1[0:2])
print(a1[::-2])

[4 5 6 4 5]
[4 5]
[5 6 4]


In [139]:
print(a2)
print(a2[::-1, ::-1]) #reverse

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [143]:
#불리언 인덱싱
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
#True인 값들만 출력

[4 5 6 4 5]
[5 6 5]


In [147]:
print(a2)
bi = np.random.randint(0, 2, (3,3), dtype=bool) #T/F 이니까 0~1 1 =T 0 =F
print(bi) #True, False 값으로 채워짐
print(a2[bi]) # True =1 인 자리 index가 리스트로 출력

#특정 조건에 따라서 특정 조건이 필터링된 배열의 원하는 값만 받을 때 주로 사용

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [ True  True False]
 [False  True False]]
[1 3 4 5 8]


In [158]:
#팬시 인덱싱
print(a1)
print([a1[0], a1[2]])
ind = [0, 2] #묶어서 한번에 전달
print(a1[ind])
ind = np.array([ [3,1],
                  [2,0] ])          
print(ind)
print(a1[ind])       # shape 이 ind 를 따라감 - 1차원 배열 -> 2차원 배열
"""
a1[3] a1[1]
a1[2] a1[0] 로 만들어짐
"""

[4 5 6 4 5]
[4, 6]
[4 6]
[[3 1]
 [2 0]]
[[4 5]
 [6 4]]


'\na1[3] a1[1]\na1[2] a1[0] 로 만들어짐\n'

In [168]:
print(a2)
row = np.array([0 ,2])
col = np.array([1, 2])

print(a2[row, col])
print(a2[:, col])
print(a2[row, :])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])
print(a2[-1:, :])
print(a2[-1, row])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]
 [7 8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]
[[7 8 9]]
[7 9]


In [185]:
#배열 값 삽입/수정/삭제/복사
#삽입 = inser() 특정위치에 값을 삽입
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1) #새로운 배열생성
print(a1) #바뀌지않음
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]
[ 1  2 10  3  4  5]


In [180]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) # axis = 0 --> 축 지정 1번째 row
print(b2)
c2 = np.insert(a2, 1, 10, axis=1) #1번째 col
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [196]:
#배열 값 수정 인덱싱으로 접근
print(a1)
a1[0] = 2
a1[1] = 3
a1[2] = 7
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0 #팬시 인덱싱 1,3,4 번 자리에 0 이 들어감 a1[x] = x에들어가면 인덱싱을 뜻함
print(a1)
a1[i] +=4
print(a1)

[9 4 7 4 4]
[2 3 7 4 4]
[9 3 7 4 4]
[9 0 7 0 0]
[9 4 7 4 4]


In [200]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0 #팬시 인덱싱
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


In [205]:
#삭제 delete() 특정위치 값 삭제
print(a1)
b1 = np.delete(a1, 1)
print(b1) #새로운 배열 생성
print(a1) # 원본 배열은 안바뀜

[9 4 7 4 4]
[9 7 4 4]
[9 4 7 4 4]


In [209]:
print(a2)
b2 = np.delete(a2, 1, axis=0) # row 1번째 삭제
print(b2)
c2 = np.delete(a2, 1, axis=1) # col 1번째 삭제
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


In [213]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2] #원본 배열에 영향을 끼침
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)   #원본 배열에 영향을 끼침 


[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [216]:
#카피를 안붙이면 서브에서 수정되는 원본도 바뀐다.
print(a2)
a2_sub_copy = a2[:2, :2].copy()  #별개의 메모리위치
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [222]:
#배열 변환 - 전치및 축 변경
print(a2)
print(a2.T) #행과 열 바뀜
    

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [224]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [227]:
#축 변경
print(a2)
print(a2.swapaxes(1,0)) # T 결과와 똑같음

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [233]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [235]:
#배열의 재구조화
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3)) # 1 > 2 차원

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [240]:
#새로운 축 추가
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [243]:
#배열 크기 변경
n2 = np.random.randint(0, 10, (2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[0 0 6 1 1]
 [0 9 2 8 9]]
[[0 0]
 [6 1]
 [1 0]
 [9 2]
 [8 9]]


In [245]:
n2.resize((5,5)) #남은 공간이 0으로 채워져 크기가 커짐
print(n2)

[[0 0 6 1 1]
 [0 9 2 8 9]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [247]:
n2.resize((3,3)) #사이즈가 줄면 삭제가 됨
print(n2)

[[0 0 6]
 [1 1 0]
 [9 2 8]]


In [250]:
#배열 추가
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.arange(10, 19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [252]:
#append
c2 = np.append(a2, b2) # 이차원배열 -> 1차원 형태로 변함 axis지정이없으면.
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [254]:
c2 = np.append(a2, b2, axis=0) # axis 지정 0 =밑으로
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [256]:
c2 = np.append(a2, b2, axis=1) # axis 지정 1 = 옆으로
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [263]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1]) # 배열 연결 concatenate

array([1, 3, 5, 2, 4, 6])

In [265]:
 c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [268]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,a2]) #기본으로 axis = 0 이기때문에 밑으로 붙음

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [270]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,a2], axis=1) #axis = 1 이기때문에 옆 으로 붙음

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [271]:
np.vstack([a2, a2]) # vertical stack = 옆 로 붙음

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [273]:
np.hstack([a2,a2]) # 옆으로 붙음

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [274]:
np.dstack([a2,a2]) # depth stack 3차원으로 연결?

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [275]:
np.stack([a2,a2]) # 새로운 차원으로 연결 2차원 -> 3차원으로 표현됨

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [278]:
#배열 분할
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5]) #기준이 되는 인덱스, 섹션 을 지정 - 받아줄 b1,c1
print(b1, c1)
b1, c1, d1, e1, f1 =np.split(a1, [2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [282]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [284]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [288]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


In [292]:
#넘파이는 벡터화 연산을 사용 , 브로드캐스팅
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [306]:
#산술 연산
a1 = np.arange(1,10)
print(a1)
print(a1+1)
print(np.add(a1,10))
print(a1-2)
print(a2)
print(np.subtract(a2, 10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1,2))
print(a1 / 2)
print(np.divide(a1, 2))
print(a1 // 2)
print(np.floor_divide(a1, 2)) # 나누고 내림
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1,2)) #나머지 연산



[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [310]:
a1 =np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[5 3 7 6 1 2 5 7 1]
[ 6  5 10 10  6  8 12 15 10]
[-4 -1 -4 -2  4  4  2  1  8]
[ 5  6 21 24  5 12 35 56  9]
[0.2        0.66666667 0.42857143 0.66666667 5.         3.
 1.4        1.14285714 9.        ]
[0 0 0 0 5 3 1 1 9]
[      1       8    2187    4096       5      36   16807 2097152       9]
[1 2 3 4 0 0 2 1 0]


In [313]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10, size=(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 * b2)
print(a2 **b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 4]
 [3 8 3]
 [3 3 1]]
[[ 4  5  7]
 [ 7 13  9]
 [10 11 10]]
[[-2 -1 -1]
 [ 1 -3  3]
 [ 4  5  8]]
[[ 3  6 12]
 [12 40 18]
 [21 24  9]]
[[0.33333333 0.66666667 0.75      ]
 [1.33333333 0.625      2.        ]
 [2.33333333 2.66666667 9.        ]]
[[0 0 0]
 [1 0 2]
 [2 2 9]]
[[ 3  6 12]
 [12 40 18]
 [21 24  9]]
[[     1      8     81]
 [    64 390625    216]
 [   343    512      9]]


In [316]:
#절대값 함수
a1 = np.random.randint(-10, 10, size= 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))


[ 5  4 -8  0 -1]
[5 4 8 0 1]
[5 4 8 0 1]


In [319]:
#제곱근 함수
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 5  4 -8  0 -1]
[25 16 64  0  1]
[2.23606798 2.                nan 0.                nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


In [322]:
#지수와 로그 함수
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1)) #지수
print(np.power(a1,2)) # 2제곱

[7 6 6 5 9]
[1096.63315843  403.42879349  403.42879349  148.4131591  8103.08392758]
[128.  64.  64.  32. 512.]
[49 36 36 25 81]


In [326]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 6 6 5 9]
[1.94591015 1.79175947 1.79175947 1.60943791 2.19722458]
[2.80735492 2.5849625  2.5849625  2.32192809 3.169925  ]
[0.84509804 0.77815125 0.77815125 0.69897    0.95424251]


In [327]:
#삼각함수
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
