In [1]:
import numpy as np

In [9]:
A = np.matrix([[1,0,0],[0,1,1]])

In [10]:
A

matrix([[1, 0, 0],
        [0, 1, 1]])

In [11]:
B = np.matrix('1 0 0 ; 0 1 1')

In [12]:
B

matrix([[1, 0, 0],
        [0, 1, 1]])

In [13]:
A = np.matrix('1 0 0 0 ; 2 1 0 0 ; 3 0 1 0; 4 0 0 1')

In [14]:
A

matrix([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 0, 1, 0],
        [4, 0, 0, 1]])

In [15]:
A.shape

(4, 4)

In [16]:
np.linalg.inv(A)

matrix([[ 1.,  0.,  0.,  0.],
        [-2.,  1.,  0.,  0.],
        [-3.,  0.,  1.,  0.],
        [-4., -0., -0.,  1.]])

In [17]:
A = np.matrix('1 2 ; 3 4 ')

In [18]:
np.linalg.inv(A)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [19]:
B = np.matrix('2 3; 4 6')

In [20]:
B

matrix([[2, 3],
        [4, 6]])

In [24]:
np.linalg.inv(B) #역행렬 존재 x 오류뜸

LinAlgError: ignored

In [25]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
A = A.reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
A = np.arange(15).reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
A.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [30]:
np.transpose(A)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [31]:
np.swapaxes(A,0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [32]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
A = np.matrix('5 7 ; -4 3')

In [36]:
np.linalg.inv(A.T)

matrix([[ 0.06976744,  0.09302326],
        [-0.1627907 ,  0.11627907]])

In [37]:
np.linalg.inv(A).T #위와같음

matrix([[ 0.06976744,  0.09302326],
        [-0.1627907 ,  0.11627907]])